### 다항회귀
- 직선으로 많은 데이터를 만족할 수 없는 선형회귀의 경우 사용
- 기존 피쳐를 조합해서 항을 늘려주는 작업 진행 => 전처리에서 진행

In [37]:
### 모듈로딩
from sklearn.preprocessing import PolynomialFeatures
import numpy as np

In [49]:
# 임의의 데이터 생성 ==> 2D
X=np.arange(10).reshape(-1,2)
y=np.arange(5)
X

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [39]:
## 피쳐2개 ==> 조합해서 늘리기
poly=PolynomialFeatures()
#poly.fit(X)
#poly.transform(X)
X1=poly.fit_transform(X) # 두번쓸일없으니 한방에 해결!

In [40]:
poly.get_feature_names_out()

array(['1', 'x0', 'x1', 'x0^2', 'x0 x1', 'x1^2'], dtype=object)

In [41]:
X1

array([[ 1.,  0.,  1.,  0.,  0.,  1.],
       [ 1.,  2.,  3.,  4.,  6.,  9.],
       [ 1.,  4.,  5., 16., 20., 25.],
       [ 1.,  6.,  7., 36., 42., 49.],
       [ 1.,  8.,  9., 64., 72., 81.]])

In [42]:
X1.shape

(5, 6)

상수제거 : include_bias = False

In [43]:
## 피쳐2개 ==> 조합해서 늘리기
poly=PolynomialFeatures(include_bias=False) # 상수제거!
#poly.fit(X)
#poly.transform(X)
X1=poly.fit_transform(X) # 두번쓸일없으니 한방에 해결!
poly.get_feature_names_out()

array(['x0', 'x1', 'x0^2', 'x0 x1', 'x1^2'], dtype=object)

In [44]:
X1

array([[ 0.,  1.,  0.,  0.,  1.],
       [ 2.,  3.,  4.,  6.,  9.],
       [ 4.,  5., 16., 20., 25.],
       [ 6.,  7., 36., 42., 49.],
       [ 8.,  9., 64., 72., 81.]])

In [45]:
X1.shape

(5, 5)

degree 증가!

In [46]:
## 피쳐2개 ==> 조합해서 늘리기
poly=PolynomialFeatures(include_bias=False,degree=3) # degree 
#poly.fit(X)
#poly.transform(X)
X1=poly.fit_transform(X) # 두번쓸일없으니 한방에 해결!
poly.get_feature_names_out()

array(['x0', 'x1', 'x0^2', 'x0 x1', 'x1^2', 'x0^3', 'x0^2 x1', 'x0 x1^2',
       'x1^3'], dtype=object)

In [47]:
X1

array([[  0.,   1.,   0.,   0.,   1.,   0.,   0.,   0.,   1.],
       [  2.,   3.,   4.,   6.,   9.,   8.,  12.,  18.,  27.],
       [  4.,   5.,  16.,  20.,  25.,  64.,  80., 100., 125.],
       [  6.,   7.,  36.,  42.,  49., 216., 252., 294., 343.],
       [  8.,   9.,  64.,  72.,  81., 512., 576., 648., 729.]])

In [48]:
print(X1.shape)

(5, 9)


### 모델에 적용

In [50]:
from sklearn.linear_model import LinearRegression

In [51]:
model=LinearRegression()
model.fit(X,y)

LinearRegression()

In [53]:
from sklearn.pipeline import Pipeline

pipe=Pipeline([('poly',poly),('lrmodel',model)])
pipe.fit(X,y)

#=> ploy 하고 lrmodel 둘다하는 model을 줘
#=> ('모델명',모델클래스)

Pipeline(steps=[('poly', PolynomialFeatures(degree=3, include_bias=False)),
                ('lrmodel', LinearRegression())])