In [1]:
import pandas as pd
import numpy as np

df=pd.read_csv('ch2_scores_em.csv',index_col='student number')
df.head()

english  mathematics
student number                      
1                    42           65
2                    69           80
3                    56           63
4                    41           63
5                    57           76

In [2]:
scores=np.array(df['english'])[:10]
scores

array([42, 69, 56, 41, 57, 48, 65, 49, 65, 58], dtype=int64)

In [3]:
scores_df=pd.DataFrame({'score':scores},index=pd.Index(['A','B','C','D','E','F','G','H','I','J']))
scores_df

score
A     42
B     69
C     56
D     41
E     57
F     48
G     65
H     49
I     65
J     58

In [4]:
print(sum(scores)/len(scores))
print(np.mean(scores))
print(scores_df.mean())

55.0
55.0
score    55.0
dtype: float64


In [5]:
sorted_scores=np.sort(scores)
sorted_scores

array([41, 42, 48, 49, 56, 57, 58, 65, 65, 69], dtype=int64)

In [6]:
n=len(sorted_scores)
if n%2==0:
    m0=sorted_scores[n//2-1]
    m1=sorted_scores[n//2]
    median=(m0+m1)/2
else:
    median=sorted_scores[(n-1)//2-1]
median

56.5

In [7]:
pd.Series([1,1,1,2,2,3]).mode()


0    1
dtype: int64

In [8]:
mean=np.mean(scores)
deviation=scores-mean
deviation

array([-13.,  14.,   1., -14.,   2.,  -7.,  10.,  -6.,  10.,   3.])

In [9]:
summeray_df=scores_df.copy()
summeray_df['deviation']=deviation
summeray_df

score  deviation
A     42      -13.0
B     69       14.0
C     56        1.0
D     41      -14.0
E     57        2.0
F     48       -7.0
G     65       10.0
H     49       -6.0
I     65       10.0
J     58        3.0

In [10]:
summeray_df.mean()

score        55.0
deviation     0.0
dtype: float64

In [11]:
np.mean(deviation**2)

86.0

In [12]:
np.var(scores)

86.0

In [13]:
scores_df.var()

score    95.555556
dtype: float64

In [15]:
summeray_df['square of deviation']=np.square(deviation)
summeray_df

score  deviation  square of deviation
A     42      -13.0                169.0
B     69       14.0                196.0
C     56        1.0                  1.0
D     41      -14.0                196.0
E     57        2.0                  4.0
F     48       -7.0                 49.0
G     65       10.0                100.0
H     49       -6.0                 36.0
I     65       10.0                100.0
J     58        3.0                  9.0

In [16]:
summeray_df.mean()

score                  55.0
deviation               0.0
square of deviation    86.0
dtype: float64

In [17]:
np.sqrt(np.var(scores,ddof=0))

9.273618495495704

In [18]:
np.std(scores,ddof=0)

9.273618495495704

to P.25