#### Tensor 이해

In [2]:
import torch

- 타입지정 Tensor 클레스 활용
    * 데이터 타입을 설정 후 생성
    * 데이터 사이즈 설정한 텐서 생성 시
    * 데이터의 자료형 변환한 텐서 생성 시 사용 

In [13]:
### 정수형 탠서 생성
data=[0.,2.8,3.1]

### 1byte int tensor 
dataTS1=torch.CharTensor(data)
dataTS11=torch.tensor(data,dtype=torch.int8)
print(dataTS1,dataTS11,sep='\n')

tensor([0, 2, 3], dtype=torch.int8)
tensor([0, 2, 3], dtype=torch.int8)


C:\Users\KDP-48\AppData\Local\Temp\ipykernel_1984\1513439104.py:5: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  dataTS1=torch.CharTensor(data)
C:\Users\KDP-48\AppData\Local\Temp\ipykernel_1984\1513439104.py:6: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  dataTS11=torch.tensor(data,dtype=torch.int8)


In [14]:
### 2byte int tensor 
dataTS1=torch.ShortTensor(data)
dataTS11=torch.tensor(data,dtype=torch.int16)
print(dataTS1,dataTS11,sep='\n')

tensor([0, 2, 3], dtype=torch.int16)
tensor([0, 2, 3], dtype=torch.int16)


C:\Users\KDP-48\AppData\Local\Temp\ipykernel_1984\1758236226.py:2: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  dataTS1=torch.ShortTensor(data)
C:\Users\KDP-48\AppData\Local\Temp\ipykernel_1984\1758236226.py:3: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  dataTS11=torch.tensor(data,dtype=torch.int16)


In [15]:
### Boolean Tensor
dataTS1=torch.BoolTensor(data)
dataTS11=torch.tensor(data,dtype=torch.bool)
print(dataTS1,dataTS11,sep='\n')

tensor([False,  True,  True])
tensor([False,  True,  True])


In [16]:
### Float Tensor
dataTS1=torch.DoubleTensor(data)
dataTS11=torch.tensor(data,dtype=torch.float64)
print(dataTS1,dataTS11,sep='\n')

tensor([0.0000, 2.8000, 3.1000], dtype=torch.float64)
tensor([0.0000, 2.8000, 3.1000], dtype=torch.float64)


- Tensor 저장 및 실행 위치 설정 ==> 속성 device 설정

In [21]:
### 저장 및 실행 위치 => CPU/GPU
DEVICE= 'cuda' if torch.cuda.is_available() else 'cpu'
DEVICE

'cpu'

In [22]:
### Float Tensor
dataTS1=torch.DoubleTensor(data)
dataTS11=torch.tensor(data,dtype=torch.float64,device=DEVICE)
print(dataTS1,dataTS11,sep='\n')

tensor([0.0000, 2.8000, 3.1000], dtype=torch.float64)
tensor([0.0000, 2.8000, 3.1000], dtype=torch.float64)
