#### Tensor의 모양/형태/shape 변경과 View Tensor

In [1]:
import torch
import numpy as np

In [2]:
dataTS=torch.arange(1,21)
print(dataTS,dataTS.ndim,dataTS.stride(),sep='\n')

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20])
1
(1,)


In [10]:
# 1D => 2D 형태/모양/shape 변경
dataTS2=dataTS.reshape((-1,5))
print(dataTS2,dataTS2.ndim,dataTS2.stride(),sep='\n')
print(f'is_contiguous() : {dataTS2.is_contiguous()}')

tensor([[77,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]])
2
(5, 1)
is_contiguous() : True


In [11]:
print(dataTS2.storage())
print(f'is_contiguous() : {dataTS2.is_contiguous()}')

 77
 2
 3
 4
 5
 6
 7
 8
 9
 10
 11
 12
 13
 14
 15
 16
 17
 18
 19
 20
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 20]
is_contiguous() : True


In [5]:
dataTS2[0][0]=77

In [6]:
dataTS,dataTS2

(tensor([77,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
         19, 20]),
 tensor([[77,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10],
         [11, 12, 13, 14, 15],
         [16, 17, 18, 19, 20]]))

In [12]:
dataTS22=dataTS2.reshape((-1,2))
print(dataTS22,dataTS22.ndim,dataTS22.stride(),sep='\n')
print(f'is_contiguous() : {dataTS2.is_contiguous()}')

tensor([[77,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]])
2
(2, 1)
is_contiguous() : True


In [22]:
## 불연속적 ==> 연속적으로 변환 
dataTS23=dataTS22.T
print(dataTS23.storage())
print(print(f'is_contiguous() : {dataTS23.is_contiguous()}'))

dTS=dataTS23.contiguous()
print(dTS.storage())
print(f'is_contiguous() : {dTS.is_contiguous()}')

 77
 2
 3
 4
 5
 6
 7
 8
 9
 10
 11
 12
 13
 14
 15
 16
 17
 18
 19
 20
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 20]
is_contiguous() : False
None
 77
 3
 5
 7
 9
 11
 13
 15
 17
 19
 2
 4
 6
 8
 10
 12
 14
 16
 18
 20
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 20]
is_contiguous() : True
