#### Tensor 이해


In [1]:
import torch


- Tensor 생성 [2] torch.rand()

In [8]:
# 0<= ~<1 범위의 임의의 숫자 1개 추출 => rand(*size)
# rand(*size) : 가변인자 ==> 0 to n dim 
torch.manual_seed(1)

dataTS1=torch.rand(3)        # 1D Vector
dataTS2=torch.rand(2,3)      # 2D Matrix
dataTS3=torch.rand(2,2,3)    # 3D 3D Tensor
dataTS1, dataTS2, dataTS3

(tensor([0.7576, 0.2793, 0.4031]),
 tensor([[0.7347, 0.0293, 0.7999],
         [0.3971, 0.7544, 0.5695]]),
 tensor([[[0.4388, 0.6387, 0.5247],
          [0.6826, 0.3051, 0.4635]],
 
         [[0.4550, 0.5725, 0.4980],
          [0.9371, 0.6556, 0.3138]]]))

- Tensor 생성 [3] torch.randn()

In [9]:
dataTS1=torch.randn(3)        # 1D Vector
dataTS2=torch.randn(2,3)      # 2D Matrix
dataTS3=torch.randn(2,2,3)    # 3D 3D Tensor
dataTS1, dataTS2, dataTS3

(tensor([-0.6919, -0.4043,  0.2222]),
 tensor([[ 0.5773, -1.7637,  0.2264],
         [-0.2355,  0.3019, -0.2770]]),
 tensor([[[ 0.4771, -0.1103,  0.2913],
          [ 0.5848,  0.2149, -0.4090]],
 
         [[-0.1663,  0.6696,  0.1177],
          [-0.3584,  0.6513, -1.0273]]]))

- Tensor생성 [4] torch.randint()

In [15]:
dataTS1=torch.randint(1,5,(3,5))   # randint(min<=,<max,(행,열))
dataTS1

tensor([[3, 3, 1, 4, 2],
        [4, 4, 2, 1, 4],
        [1, 4, 1, 3, 1]])

In [16]:
# 2D Vector
dataTS1=torch.randint(1,46,(4,6))
dataTS1

tensor([[26,  1, 45, 43,  7, 23],
        [ 1, 17, 37, 44, 38, 11],
        [ 1, 45, 22, 45, 35, 25],
        [21, 32, 25,  2, 36, 33]])