### CHAP.1

- 배열(Array) 구조 이해하기

In [2]:
l=[[1,2,3],[4,5,6]]
type(l)

list

In [3]:
print(l[0])
print(l[1])

[1, 2, 3]
[4, 5, 6]


In [4]:
for i,a in enumerate(l):
    for j,b in enumerate(a):
        print(l[i][j])

1
2
3
4
5
6


In [6]:
np.__version__

'1.26.4'

In [7]:
import numpy as np
for i in dir(np.ndarray):
    if not i.startswith("_"):
        if type(np.ndarray.__dict__[i]) != type(np.ndarray.var):
            print(i)

T
base
ctypes
data
dtype
flags
flat
imag
itemsize
nbytes
ndim
real
shape
size
strides


In [14]:
l=[1,2,3,4]
a=np.array(l)
print(a)
print(type(a))
t=(1,2,3,4)
b=np.array(t)
print(b)
print(type(b))

[1 2 3 4]
<class 'numpy.ndarray'>
[1 2 3 4]
<class 'numpy.ndarray'>


In [15]:
print(a.data)
print(a.data.obj)
print(type(a.data.obj))

[1 2 3 4]
<class 'numpy.ndarray'>


In [19]:
e=np.array(l,dtype=np.float64)
print(e)
print(e.dtype)

array([1., 2., 3., 4.])

In [20]:
a2=np.array([[1,2,3],[4,5,6]])
print(a2.shape)
print(a2.ndim)
print(a2.dtype)
print(a2.itemsize)
print(a2.size)
print(a2.strides)

(2, 3)
2
int32
4
6
(12, 4)


In [21]:
print(np.ndarray.__bases__)
print(np.matrix.__bases__)

(<class 'object'>,)
(<class 'numpy.ndarray'>,)


- 넘파이 묘듈의 함수 특징

In [23]:
print((a != 0).any)
print(np.any)
print(np.ndarray.any is np.core.fromnumeric.any)

<built-in method any of numpy.ndarray object at 0x0000018F4A4EA670>
<function any at 0x0000018F49DA4900>
False


In [25]:
np_=set(dir(np))
nd_=set(dir(np.ndarray))
npd_=np_ & nd_
print(len(npd_))

count=0
for i in list(npd_):
    count+=1
    print(i,end=' ')
    if count%5==0:
        print()

48
dot ptp choose trace dtype 
repeat put mean all argsort 
nonzero squeeze transpose conj round 
cumprod var sum partition cumsum 
nbytes reshape max ravel size 
argmin compress any min argpartition 
ndim real sort imag take 
__doc__ copy swapaxes searchsorted argmax 
prod std __dir__ conjugate shape 
diagonal resize clip 

In [28]:
a=dir(np)
print(np.ufunc)

<class 'numpy.ufunc'>


In [29]:
count=0
for i in a:
    continue
if type(np.__dict__[i])==np.ufunc:
    print(i,end=' ')
    count+=1
    if count%5==0:
        print()

In [32]:
a=np.arange(6,10)
print(a)
b=np.arange(10,14)
print(b)
c=a*b
print(c)

[6 7 8 9]
[10 11 12 13]
[ 60  77  96 117]


In [36]:
a2=np.array([1,2,3,4])
print(a2)
a2=a2.reshape(2,2)
print(a2)
print(np.sum(a2))
print(np.sum(a2,axis=0))
print(np.sum(a2,axis=1))

[1 2 3 4]
[[1 2]
 [3 4]]
10
[4 6]
[3 7]


115.P